exclude: 'plugins/**'


linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true
    style: short

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties:
      - print-color-adjust

  SelectorDepth:
    enabled: true
    max_depth: 4

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: true
